// SHADOW GUILD — CITY MAP v2.0
// Axial Hex Grid (q, r) — PlanetSide 2 Lattice System
// Distance formula: (abs(q1-q2) + abs(q1+r1-q2-r2) + abs(r1-r2)) / 2
// All connections are bidirectional and adjacent (distance = 1)

export const DISTRICTS = {
	Z1: { id: 'Z1', name: 'NEON_CORE',      color: '#ffc174', desc: 'High tech, high risk. Heart of Aetheria.', lootMultiplier: 4.0, heatDecayBase: 0.1 },
	Z2: { id: 'Z2', name: 'INDUSTRIAL_WASTES', color: '#ff6b35', desc: 'Raw resources. Gold focus. Toxic.', lootMultiplier: 2.0, heatDecayBase: 0.2 },
	Z3: { id: 'Z3', name: 'EASTERN_TECH',      color: '#00d4ff', desc: 'Encryption and security complexes.', lootMultiplier: 2.5, heatDecayBase: 0.15 },
	Z4: { id: 'Z4', name: 'WESTERN_SLUMS',     color: '#b347ff', desc: 'Stealth and black market networks.', lootMultiplier: 1.0, heatDecayBase: 0.3 },
	Z5: { id: 'Z5', name: 'CORP_CITADEL',      color: '#ff2244', desc: 'Endgame zone. GID controlled.', lootMultiplier: 8.0, heatDecayBase: 0.05 },
	Z6: { id: 'Z6', name: 'THE_UNDERBELLY',    color: '#22ff88', desc: 'Hidden. Accessed via Subway Nexus.', lootMultiplier: 3.0, heatDecayBase: 0.4 },
	Z7: { id: 'Z7', name: 'BUFFER_DISTRICTS',  color: '#888899', desc: 'Transition zones. Contested.', lootMultiplier: 1.5, heatDecayBase: 0.2 },
};

// EFFECT HOOKS — applied to player when hex is under player control
const EFFECTS = {
	none:            { type: 'none' },
	xp_boost:        { type: 'xp_boost',       value: 0.25,  desc: 'XP +25%' },
	xp_boost_major:  { type: 'xp_boost',       value: 0.50,  desc: 'XP +50%' },
	siphon_boost:    { type: 'siphon_rate',     value: 0.15,  desc: 'Siphon success +15%' },
	stamina_regen:   { type: 'stamina_regen',   value: 1,     desc: 'Stamina regen +1/s' },
	stamina_major:   { type: 'stamina_regen',   value: 2,     desc: 'Stamina regen +2/s' },
	heat_decay:      { type: 'heat_decay',      value: 0.5,   desc: 'Heat decay +0.5/s' },
	heat_decay_major:{ type: 'heat_decay',      value: 1.5,   desc: 'Heat decay +1.5/s' },
	gold_boost:      { type: 'gold_mult',       value: 0.20,  desc: 'Gold +20%' },
	gold_major:      { type: 'gold_mult',       value: 0.40,  desc: 'Gold +40%' },
	runner_speed:    { type: 'runner_speed',    value: 0.15,  desc: 'Runner speed +15%' },
	runner_major:    { type: 'runner_speed',    value: 0.30,  desc: 'Runner speed +30%' },
	bust_threshold:  { type: 'bust_threshold',  value: 10,    desc: 'Bust threshold +10' },
	loot_tier:       { type: 'loot_tier',       value: 1,     desc: 'Loot tier +1' },
	dark_market_cd:  { type: 'dark_market_cd',  value: -1800, desc: 'Dark Market CD -30min' },
	intel_discount:  { type: 'intel_discount',  value: 0.20,  desc: 'Intel upgrades -20%' },
	offline_cap:     { type: 'offline_cap',     value: 7200,  desc: 'Offline cap +2h' },
	inv_slots:       { type: 'inv_slots',       value: 4,     desc: '+4 inventory slots' },
	crit_chance:     { type: 'crit_chance',     value: 0.05,  desc: 'Crit chance +5%' },
	rep_boost:       { type: 'rep_boost',       value: 0.25,  desc: 'REP gains +25%' },
};

export const CITY_MAP = {

	// ═══════════════════════════════════════════════════
	// Z1 — NEON CORE (center cluster)
	// ═══════════════════════════════════════════════════

	'aetheria_spire': {
		id: 'aetheria_spire',
		label: 'AETHERIA SPIRE',
		type: 'mega_facility',
		districtId: 'Z1',
		layer: 'endgame',
		role: 'Command Node — controls all district bonuses',
		icon: '◉',
		q: 0, r: 0,
		connections: ['neon_exchange', 'relay_node_alpha', 'relay_node_beta', 'relay_node_gamma', 'data_cathedral', 'signal_crown'],
		captureStatus: 'contested',
		faction: 'GID',
		effectHooks: [EFFECTS.xp_boost_major, EFFECTS.gold_major, EFFECTS.siphon_boost],
		lootMultiplier: 3.0,
		captureTime: 120,
		flavor: 'THE EYE runs from here. Take it and the city is yours.',
	},

	'neon_exchange': {
		id: 'neon_exchange',
		label: 'NEON EXCHANGE',
		type: 'tech_plant',
		districtId: 'Z1',
		layer: 'core',
		role: 'Quantum Data Center — global XP/Siphon buffs',
		icon: '◉',
		q: 1, r: -1,
		connections: ['aetheria_spire', 'uplink_tower', 'grid_station_7', 'ghost_alley'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.xp_boost, EFFECTS.siphon_boost],
		lootMultiplier: 2.0,
		captureTime: 60,
		flavor: 'Every credit in this city flows through Neon Exchange.',
	},

	'relay_node_alpha': {
		id: 'relay_node_alpha',
		label: 'RELAY NODE ALPHA',
		type: 'outpost',
		districtId: 'Z1',
		layer: 'core',
		role: 'Signal amplifier',
		icon: '⬡',
		q: 0, r: -1,
		connections: ['aetheria_spire', 'uplink_tower', 'northern_warpgate', 'data_cathedral'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.heat_decay],
		lootMultiplier: 1.2,
		captureTime: 30,
		flavor: 'Relay nodes are how Zero finds you.',
	},

	'relay_node_beta': {
		id: 'relay_node_beta',
		label: 'RELAY NODE BETA',
		type: 'outpost',
		districtId: 'Z1',
		layer: 'core',
		role: 'Signal amplifier',
		icon: '⬡',
		q: 1, r: 0,
		connections: ['aetheria_spire', 'grid_station_7', 'corp_perimeter_west', 'signal_crown'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.stamina_regen],
		lootMultiplier: 1.2,
		captureTime: 30,
		flavor: 'They upgraded the security last cycle. Watch the cameras.',
	},

	'relay_node_gamma': {
		id: 'relay_node_gamma',
		label: 'RELAY NODE GAMMA',
		type: 'outpost',
		districtId: 'Z1',
		layer: 'core',
		role: 'Signal amplifier',
		icon: '⬡',
		q: -1, r: 1,
		connections: ['aetheria_spire', 'slum_nexus', 'underbelly_access', 'ghost_alley'],
		captureStatus: 'player',
		faction: 'PLAYER',
		effectHooks: [EFFECTS.gold_boost],
		lootMultiplier: 1.3,
		captureTime: 30,
		flavor: 'Your first foothold in the city center.',
	},

	'data_cathedral': {
		id: 'data_cathedral',
		label: 'DATA CATHEDRAL',
		type: 'amp_station',
		districtId: 'Z1',
		layer: 'core',
		role: 'Power Grid Reactor — stamina and energy buffs',
		icon: '◉',
		q: -1, r: 0,
		connections: ['aetheria_spire', 'relay_node_alpha', 'ghost_alley', 'western_warpgate'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.stamina_major, EFFECTS.bust_threshold],
		lootMultiplier: 2.0,
		captureTime: 60,
		flavor: 'Power flows from Data Cathedral. Cut it and the city goes dark.',
	},

	'signal_crown': {
		id: 'signal_crown',
		label: 'SIGNAL CROWN',
		type: 'bio_lab',
		districtId: 'Z1',
		layer: 'core',
		role: 'Neural Forge — runner survival and heat decay buffs',
		icon: '◉',
		q: 0, r: 1,
		connections: ['aetheria_spire', 'relay_node_beta', 'industrial_gate', 'underbelly_access'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.heat_decay_major, EFFECTS.runner_speed],
		lootMultiplier: 2.0,
		captureTime: 60,
		flavor: 'Neural Forge. Your runners train here or they die out there.',
	},

	// ═══════════════════════════════════════════════════
	// Z3 — EASTERN TECH (encryption and security)
	// ═══════════════════════════════════════════════════

	'uplink_tower': {
		id: 'uplink_tower',
		label: 'UPLINK TOWER',
		type: 'tech_plant',
		districtId: 'Z3',
		layer: 'mid',
		role: 'Quantum Data Center — encryption focus',
		icon: '◉',
		q: 2, r: -2,
		connections: ['neon_exchange', 'relay_node_alpha', 'cipher_vault', 'eastern_buffer_1'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.siphon_boost, EFFECTS.intel_discount],
		lootMultiplier: 1.8,
		captureTime: 60,
		flavor: 'All encrypted comms pass through Uplink Tower.',
	},

	'cipher_vault': {
		id: 'cipher_vault',
		label: 'CIPHER VAULT',
		type: 'outpost',
		districtId: 'Z3',
		layer: 'mid',
		role: 'Encryption node',
		icon: '⬡',
		q: 3, r: -3,
		connections: ['uplink_tower', 'eastern_buffer_1', 'sec_array'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.loot_tier],
		lootMultiplier: 1.5,
		captureTime: 45,
		flavor: 'Cipher Vault holds keys to every corp network in the city.',
	},

	'eastern_buffer_1': {
		id: 'eastern_buffer_1',
		label: 'EASTERN BUFFER',
		type: 'empty_block',
		districtId: 'Z7',
		layer: 'buffer',
		role: 'Transition zone',
		icon: '▪',
		q: 3, r: -2,
		connections: ['uplink_tower', 'cipher_vault', 'sec_array', 'eastern_warpgate'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.none],
		lootMultiplier: 1.0,
		captureTime: 20,
		flavor: 'Empty. Or so they say.',
	},

	'sec_array': {
		id: 'sec_array',
		label: 'SECURITY ARRAY',
		type: 'amp_station',
		districtId: 'Z3',
		layer: 'mid',
		role: 'Power Grid Reactor — security focus',
		icon: '◉',
		q: 4, r: -3,
		connections: ['cipher_vault', 'eastern_buffer_1', 'eastern_warpgate'],
		captureStatus: 'GID',
		faction: 'GID',
		effectHooks: [EFFECTS.bust_threshold, EFFECTS.heat_decay],
		lootMultiplier: 1.8,
		captureTime: 60,
		flavor: 'GID runs THE EYE surveillance from here.',
	},

	'eastern_warpgate': {
		id: 'eastern_warpgate',
		label: 'EASTERN WARPGATE',
		type: 'warpgate',
		districtId: 'Z7',
		layer: 'edge',
		role: 'GID spawn point — hardened position',
		icon: '⚠',
		q: 5, r: -4,
		connections: ['eastern_buffer_1', 'sec_array'],
		captureStatus: 'GID',
		faction: 'GID',
		effectHooks: [EFFECTS.none],
		lootMultiplier: 0.5,
		captureTime: 999,
		flavor: 'GID command. You would have to be insane to come here.',
	},

	// ═══════════════════════════════════════════════════
	// Z4 — WESTERN SLUMS (stealth and black market)
	// ═══════════════════════════════════════════════════

	'ghost_alley': {
		id: 'ghost_alley',
		label: 'GHOST ALLEY',
		type: 'bio_lab',
		districtId: 'Z4',
		layer: 'mid',
		role: 'Neural Forge — stealth focus',
		icon: '◉',
		q: -2, r: 1,
		connections: ['relay_node_gamma', 'neon_exchange', 'data_cathedral', 'slum_nexus', 'black_den'],
		captureStatus: 'player',
		faction: 'PLAYER',
		effectHooks: [EFFECTS.heat_decay, EFFECTS.runner_speed],
		lootMultiplier: 1.6,
		captureTime: 45,
		flavor: 'Ghost Alley. Nobody asks questions here.',
	},

	'black_den': {
		id: 'black_den',
		label: 'BLACK MARKET DEN',
		type: 'outpost',
		districtId: 'Z4',
		layer: 'mid',
		role: 'Underground economy hub',
		icon: '⬡',
		q: -3, r: 2,
		connections: ['ghost_alley', 'slum_nexus', 'western_buffer_1'],
		captureStatus: 'player',
		faction: 'PLAYER',
		effectHooks: [EFFECTS.dark_market_cd, EFFECTS.gold_boost],
		lootMultiplier: 1.4,
		captureTime: 30,
		flavor: 'Whatever you need. No questions. Bring credits.',
	},

	'slum_nexus': {
		id: 'slum_nexus',
		label: 'SLUM NEXUS',
		type: 'tech_plant',
		districtId: 'Z4',
		layer: 'mid',
		role: 'Quantum Data Center — black market data',
		icon: '◉',
		q: -2, r: 2,
		connections: ['relay_node_gamma', 'ghost_alley', 'black_den', 'western_buffer_1', 'western_warpgate'],
		captureStatus: 'player',
		faction: 'PLAYER',
		effectHooks: [EFFECTS.rep_boost, EFFECTS.intel_discount],
		lootMultiplier: 1.7,
		captureTime: 45,
		flavor: 'Slum Nexus. Where data goes to disappear.',
	},

	'western_buffer_1': {
		id: 'western_buffer_1',
		label: 'WESTERN BUFFER',
		type: 'empty_block',
		districtId: 'Z7',
		layer: 'buffer',
		role: 'Transition zone',
		icon: '▪',
		q: -3, r: 3,
		connections: ['black_den', 'slum_nexus', 'western_warpgate'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.none],
		lootMultiplier: 1.0,
		captureTime: 20,
		flavor: 'Rubble. But rubble has uses.',
	},

	'western_warpgate': {
		id: 'western_warpgate',
		label: 'WESTERN WARPGATE',
		type: 'warpgate',
		districtId: 'Z4',
		layer: 'edge',
		role: 'Player spawn point — starting position',
		icon: '⚠',
		q: -4, r: 4,
		connections: ['western_buffer_1', 'slum_nexus', 'data_cathedral'],
		captureStatus: 'player',
		faction: 'PLAYER',
		effectHooks: [EFFECTS.stamina_regen, EFFECTS.heat_decay],
		lootMultiplier: 0.8,
		captureTime: 999,
		flavor: 'Your base. The only place in the city that is truly yours.',
	},

	// ═══════════════════════════════════════════════════
	// Z2 — INDUSTRIAL WASTES (gold focus)
	// ═══════════════════════════════════════════════════

	'grid_station_7': {
		id: 'grid_station_7',
		label: 'GRID STATION 7',
		type: 'amp_station',
		districtId: 'Z2',
		layer: 'mid',
		role: 'Power Grid Reactor — industrial energy',
		icon: '◉',
		q: 2, r: 0,
		connections: ['relay_node_beta', 'neon_exchange', 'industrial_gate', 'refinery_block'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.gold_boost, EFFECTS.stamina_regen],
		lootMultiplier: 1.6,
		captureTime: 45,
		flavor: 'Grid Station 7 powers the factories. And the factories power everything.',
	},

	'industrial_gate': {
		id: 'industrial_gate',
		label: 'INDUSTRIAL GATE',
		type: 'outpost',
		districtId: 'Z2',
		layer: 'mid',
		role: 'Factory checkpoint',
		icon: '⬡',
		q: 2, r: 1,
		connections: ['signal_crown', 'grid_station_7', 'refinery_block', 'southern_buffer_1'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.gold_boost],
		lootMultiplier: 1.4,
		captureTime: 30,
		flavor: 'They import raw materials. You export data.',
	},

	'refinery_block': {
		id: 'refinery_block',
		label: 'REFINERY BLOCK',
		type: 'tech_plant',
		districtId: 'Z2',
		layer: 'mid',
		role: 'Quantum Data Center — resource processing',
		icon: '◉',
		q: 3, r: 0,
		connections: ['grid_station_7', 'industrial_gate', 'southern_buffer_1', 'scrapyard'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.gold_major, EFFECTS.runner_major],
		lootMultiplier: 2.0,
		captureTime: 60,
		flavor: 'Refinery Block. They refine ore. You refine intelligence.',
	},

	'scrapyard': {
		id: 'scrapyard',
		label: 'SCRAPYARD OMEGA',
		type: 'outpost',
		districtId: 'Z2',
		layer: 'outer',
		role: 'Salvage operations',
		icon: '⬡',
		q: 4, r: -1,
		connections: ['refinery_block', 'southern_buffer_1'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.inv_slots],
		lootMultiplier: 1.3,
		captureTime: 25,
		flavor: 'Everything the city throws away. Including data it thought was deleted.',
	},

	'southern_buffer_1': {
		id: 'southern_buffer_1',
		label: 'SOUTHERN BUFFER',
		type: 'empty_block',
		districtId: 'Z7',
		layer: 'buffer',
		role: 'Transition zone',
		icon: '▪',
		q: 3, r: 1,
		connections: ['industrial_gate', 'refinery_block', 'scrapyard', 'southern_warpgate'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.none],
		lootMultiplier: 1.0,
		captureTime: 20,
		flavor: 'Abandoned industrial zone. Perfect for a meeting.',
	},

	// ═══════════════════════════════════════════════════
	// Z5 — CORP CITADEL (endgame, GID controlled)
	// ═══════════════════════════════════════════════════

	'corp_perimeter_west': {
		id: 'corp_perimeter_west',
		label: 'CORP PERIMETER WEST',
		type: 'outpost',
		districtId: 'Z5',
		layer: 'outer',
		role: 'Corporate security checkpoint',
		icon: '⚠',
		q: 2, r: -1,
		connections: ['relay_node_beta', 'aetheria_spire', 'corp_inner_ring'],
		captureStatus: 'GID',
		faction: 'GID',
		effectHooks: [EFFECTS.bust_threshold],
		lootMultiplier: 2.2,
		captureTime: 75,
		flavor: 'First wall of the Corp Citadel. Heavy surveillance.',
	},

	'corp_inner_ring': {
		id: 'corp_inner_ring',
		label: 'CORP INNER RING',
		type: 'amp_station',
		districtId: 'Z5',
		layer: 'outer',
		role: 'Power Grid Reactor — corporate power',
		icon: '⚠',
		q: 3, r: -2,
		connections: ['corp_perimeter_west', 'aetheria_forge', 'eastern_buffer_1'],
		captureStatus: 'GID',
		faction: 'GID',
		effectHooks: [EFFECTS.gold_major, EFFECTS.loot_tier],
		lootMultiplier: 2.5,
		captureTime: 90,
		flavor: 'The inner ring. If you are here, THE EYE already knows.',
	},

	'aetheria_forge': {
		id: 'aetheria_forge',
		label: 'AETHERIA FORGE',
		type: 'bio_lab',
		districtId: 'Z5',
		layer: 'outer',
		role: 'Neural Forge — corporate bio-division',
		icon: '⚠',
		q: 4, r: -2,
		connections: ['corp_inner_ring', 'northern_warpgate'],
		captureStatus: 'GID',
		faction: 'GID',
		effectHooks: [EFFECTS.crit_chance, EFFECTS.xp_boost],
		lootMultiplier: 2.8,
		captureTime: 90,
		flavor: 'Aether-Biotech makes their weapons here. Neural and otherwise.',
	},

	'northern_warpgate': {
		id: 'northern_warpgate',
		label: 'NORTHERN WARPGATE',
		type: 'warpgate',
		districtId: 'Z5',
		layer: 'edge',
		role: 'Omniguard spawn — elite corporate forces',
		icon: '⚠',
		q: 5, r: -3,
		connections: ['aetheria_forge', 'relay_node_alpha'],
		captureStatus: 'GID',
		faction: 'OMNIGUARD',
		effectHooks: [EFFECTS.none],
		lootMultiplier: 0.5,
		captureTime: 999,
		flavor: 'Omniguard deploy here. Do not engage.',
	},

	// ═══════════════════════════════════════════════════
	// Z6 — THE UNDERBELLY (hidden, subway access)
	// ═══════════════════════════════════════════════════

	'underbelly_access': {
		id: 'underbelly_access',
		label: 'SUBWAY NEXUS',
		type: 'outpost',
		districtId: 'Z6',
		layer: 'hidden',
		role: 'Underground access point',
		icon: '⬡',
		q: 0, r: 2,
		connections: ['signal_crown', 'relay_node_gamma', 'deep_server_farm', 'forgotten_terminal'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.offline_cap],
		lootMultiplier: 1.5,
		captureTime: 40,
		flavor: 'The entrance to the Underbelly. Most people do not know it exists.',
	},

	'deep_server_farm': {
		id: 'deep_server_farm',
		label: 'DEEP SERVER FARM',
		type: 'tech_plant',
		districtId: 'Z6',
		layer: 'hidden',
		role: 'Quantum Data Center — hidden infrastructure',
		icon: '◉',
		q: -1, r: 3,
		connections: ['underbelly_access', 'forgotten_terminal', 'zero_station'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.xp_boost, EFFECTS.siphon_boost, EFFECTS.rep_boost],
		lootMultiplier: 2.2,
		captureTime: 60,
		flavor: 'Servers that do not appear on any map. Zero built these.',
	},

	'forgotten_terminal': {
		id: 'forgotten_terminal',
		label: 'FORGOTTEN TERMINAL',
		type: 'outpost',
		districtId: 'Z6',
		layer: 'hidden',
		role: 'Abandoned access node',
		icon: '⬡',
		q: 0, r: 3,
		connections: ['underbelly_access', 'deep_server_farm', 'southern_warpgate'],
		captureStatus: 'neutral',
		faction: null,
		effectHooks: [EFFECTS.dark_market_cd, EFFECTS.inv_slots],
		lootMultiplier: 1.8,
		captureTime: 35,
		flavor: 'Someone was here before you. The logs go back thirty years.',
	},

	'zero_station': {
		id: 'zero_station',
		label: 'ZERO STATION',
		type: 'mega_facility',
		districtId: 'Z6',
		layer: 'hidden',
		role: 'Zero\'s hidden base — ultimate reward',
		icon: '◉',
		q: -1, r: 4,
		connections: ['deep_server_farm'],
		captureStatus: 'neutral',
		faction: 'ZERO',
		effectHooks: [EFFECTS.xp_boost_major, EFFECTS.gold_major, EFFECTS.crit_chance, EFFECTS.runner_major],
		lootMultiplier: 4.0,
		captureTime: 180,
		flavor: '"You found me. I wondered if you would." — Zero',
	},

	// ═══════════════════════════════════════════════════
	// Z7 — BUFFER / SOUTHERN (transition zones)
	// ═══════════════════════════════════════════════════

	'southern_warpgate': {
		id: 'southern_warpgate',
		label: 'SOUTHERN WARPGATE',
		type: 'warpgate',
		districtId: 'Z7',
		layer: 'edge',
		role: 'Omniguard secondary spawn',
		icon: '⚠',
		q: 2, r: 2,
		connections: ['southern_buffer_1', 'forgotten_terminal'],
		captureStatus: 'GID',
		faction: 'OMNIGUARD',
		effectHooks: [EFFECTS.none],
		lootMultiplier: 0.5,
		captureTime: 999,
		flavor: 'Secondary Omniguard position. Less defended than Northern.',
	},

};


// ═══════════════════════════════════════════════════
// MAP STATS
// ═══════════════════════════════════════════════════

export const MAP_STATS = {
	totalHexes: Object.keys(CITY_MAP).length, // = 31
	byType: {
		mega_facility: 3,
		tech_plant: 5,
		amp_station: 4,
		bio_lab: 3,
		outpost: 9,
		empty_block: 3,
		warpgate: 4,
	},
	byFaction: {
		PLAYER: 4,
		GID: 6,
		OMNIGUARD: 2,
		ZERO: 1,
		neutral: Object.values(CITY_MAP).filter(h => !h.faction).length, // = 18
	},
	byDistrict: {
		Z1: 7,   // aetheria_spire, neon_exchange, relay_node_alpha, relay_node_beta, relay_node_gamma, data_cathedral, signal_crown
		Z2: 4,   // grid_station_7, industrial_gate, refinery_block, scrapyard
		Z3: 3,   // uplink_tower, cipher_vault, sec_array
		Z4: 4,   // ghost_alley, black_den, slum_nexus, western_warpgate
		Z5: 4,   // corp_perimeter_west, corp_inner_ring, aetheria_forge, northern_warpgate
		Z6: 4,   // underbelly_access, deep_server_farm, forgotten_terminal, zero_station
		Z7: 5,   // eastern_buffer_1, eastern_warpgate, western_buffer_1, southern_buffer_1, southern_warpgate
	},
};